# Generated by Django 3.1 on 2020-08-23 14:22

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('image_uri', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('attending', models.BooleanField(default=False)),
                ('dietary_restrictions', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('VEGAN', 'VEGAN'), ('VEGETARIAN', 'VEGETARIAN'), ('GLUTEN-FREE', 'GLUTEN-FREE'), ('DAIRY-FREE', 'DAIRY-FREE'), ('OTHER', 'OTHER')], max_length=45)),
                ('dietary_notes', models.CharField(blank=True, max_length=1000)),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='rsvp.group')),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rsvp.song')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
            },
        ),
    ]
