# Generated by Django 3.1 on 2020-08-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_song_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
