# Generated by Django 3.1 on 2020-08-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0004_auto_20200823_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='count',
        ),
    ]
